
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Aug 10 17:50:17 CST 2019
//----------------------------------------------------

package Practica1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 10;
  public static final int CLAVES = 21;
  public static final int POR = 8;
  public static final int PUNTOYCOMA = 5;
  public static final int LEER_ARCHIVO = 26;
  public static final int IMPRIMIR = 32;
  public static final int ENTERO = 34;
  public static final int CONTAR = 28;
  public static final int SUMAR = 27;
  public static final int LLAVE_C = 12;
  public static final int COMENTARIO_LINEA = 36;
  public static final int LLAVE_A = 11;
  public static final int GRAFICAR = 33;
  public static final int CONTAR_SI = 30;
  public static final int IGUAL = 2;
  public static final int ARCHIVO = 23;
  public static final int ADMI_C = 17;
  public static final int DIV = 9;
  public static final int OBTENER_SI = 31;
  public static final int ID = 35;
  public static final int EOF = 0;
  public static final int COMILLAS = 3;
  public static final int COMENTARIO_VARIASL = 37;
  public static final int error = 1;
  public static final int COMA = 4;
  public static final int CADENA = 38;
  public static final int CORH_C = 14;
  public static final int MENOS = 7;
  public static final int CORH_A = 13;
  public static final int MENOR = 18;
  public static final int PAR_C = 16;
  public static final int PAR_A = 15;
  public static final int MAYOR = 19;
  public static final int NUMERICO = 24;
  public static final int PUNTO = 20;
  public static final int REGISTROS = 22;
  public static final int TIPO_CADENA = 25;
  public static final int PROMEDIO = 29;
  public static final int MAS = 6;
}

